### ISSUE TITLE
Modular Refactor

### ISSUE THREAD

**Issue by valkyrienyanko** [kamilbakierzynski/js_discord_bot#65]
Your functions and events in your `bot.js` file could be spread across multiple files.

e.g. Your functions could be in a file called functions.js under a folder called Modules
e.g. Your events (`ready.js`, `message.js`) could be in a folder called Events

I can get started on this if you want, let me know and I'll do it when I have time.

**Comment by kamilbakierzynski** [comment]
Thanks for your advice. I know that they should be but I was busy trying to make it work as soon as I can so it looks messy. 

My goal is to learn JS so I have to do it myself just to know how to do this :)
